### ISSUE TITLE
What is the purpose of this repository?

### ISSUE THREAD

**Issue by LFSaw** [supercollider/incubator#1]
Following [discussions](
https://www.listarc.bham.ac.uk/lists/sc-dev/msg58910.htm) on the sc-dev mailinglist, I open this issue for general discussion.

My proposed fix is to close this repository in favour of individual, user-hosted repositories for external sc plugins, provided

> * authoring (done! cookecutter, awesome!)
> * distributing
> * finding
> * installing

> individually-built plugins. Before starting any migrations. WIP is ok (i.e. we don't need a package manager before getting started), as long as it works.

(Thanks for the wording, michael). I’d add to this that IMHO this repository was added too early in the discussion process and its purpose is not clearly defined, hence the title of this issue.

**Comment by brianlheim** [comment]
imho a proposal to close this is also premature and needlessly aggressive toward nathan. let's take some more time to continue discussing it on the mailing list, and not escalate things this way.

also, the link you posted is broken.

**Comment by LFSaw** [comment]
brian,

I am not agressive towards you or nathan, I simply try to explain myself.
I offer a space for discussion.

If you see the link to be broken, you might also take the time to correct this.
I am out of this discussion now, I am tired of the way I am treated here.

**Comment by muellmusik** [comment]
> needlessly aggressive

I'm fairly sure that wasn't the intention. There seems to be a lot of disagreement and need for further discussion around this, so perhaps it's more productive to work towards agreement than focus on who did what too early.

**Comment by brianlheim** [comment]
> I'm fairly sure that wasn't the intention.

my point was not about the intention, it was about the effect. we can discuss this without penalizing people for their enthusiasm.

**Comment by muellmusik** [comment]
> we can discuss this without penalizing people for their enthusiasm.

Or with penalising people for raising concerns. Calling them aggressive would be an example of that, IMHO. I'm sure you agree that intention matters, especially in cases of misinterpretation.

Till seems to be withdrawing as well, btw.

**Comment by telephon** [comment]
The more work is already invested, the more concerns with its implications are prone to be perceived as aggressive or dismissive.

**Comment by muellmusik** [comment]
> The more work is already invested, the more concerns with its implications are prone to be perceived as aggressive or dismissive.

Yes. And the stronger the pushback, the more likely that people will feel their concerns and contributions to discussion are considered valueless. This has happened several times here recently (and of course countless times before). In the absence of direct interaction (tone of voice, facial expression, body language, and other primate stuff) it's even easier to get this wrong. A little patience and benefit of the doubt can go a long way.

**Comment by joslloand** [comment]
> also, the link you posted is broken.

Here's the link: [[sc-dev] the future of sc3-plugins](https://www.listarc.bham.ac.uk/lists/sc-dev/msg58832.html)

**Comment by joslloand** [comment]
In my reading of @snappizz original points 3 & 4, the incubator appears as a holding pen with an intention to move later migrate these held plugins to the core.

I'm an advocate for [_reducing_ the size of the core](https://www.listarc.bham.ac.uk/lists/sc-dev/msg58919.html), rather than increasing it...

**Comment by telephon** [comment]
Hm, ok. So what about ugens in sc3-plugins that are useful and well written whose authors have no time to rewrite them or are not active any more? Should we let them erode? Or are there none of those perhaps? (I am not sure!)

**Comment by joslloand** [comment]
@telephon good question....

Which also brings up, what do we think is (or was?)† the purpose of _sc3-plugins_? The thing I'm worried about is the role of _sc3-plugins_ or _incubator_ as a staging post before hitting the core, as this implies an ever expanding core.

Obviously, what this discussion is really about is how to preserve what is great about _sc3-plugins_ while moving forward to something more reliable and maintainable. My feeling is that in the long term some sort of package management system along the lines of Quarks-for-UGens would offer advantages.

Yeah, but what about the short term?


† @joshpar could clarify his view of the initial intentions behind _sc3-plugins_.

**Comment by joshpar** [comment]
"Intent' is a strong word in this context. It was a place for myself and blackrain (then others) to release things that we thought were cool and wanted to share. Platforms were limited back then, and it was just useful. It gave us a way to also have students in my classes at the time have an easy way to pull down pre-compiled plugins that I taught off of. Since these were the first user-contributed plugins, the main concern was 'does it compile and run?'. It wasn't seen by me as an incubator, but over time a number of things that were in sc3-plugins were pulled in ... not because of any set process, but because enough people thought it made sense (reverbs, Warp1... BEQSuite...).

**Comment by patrickdupuis** [comment]
@joslloand What exactly are your concerns with regards to "an ever expanding core"? I believe that most SuperCollider users would welcome a greater number of quality UGens inside the core library.

**Comment by jamshark70** [comment]
I'll summarize his point. If there's an "incubator," it signals an intent to grow the core set of plugins indefinitely. But developer resources to maintain a continually growing core are finite.

I find that part of his point convincing.

He's also suggested reducing core to a minimal set, and making it easy to install additional plugins. I don't see how we can do that, practically, without upsetting large numbers of users who would suddenly have to add extensions for things that used to work out of the box.

**Comment by snappizz** [comment]
please use the mailing list for discussion, not here, thanks
